// AUTO-GENERATED by scripts/sync-methodology.mjs — do not edit by hand.
// The number of methodology writeups in methodology/. Import this instead of
// hardcoding a count (it drifted to 16/21 against an actual 22 before this).
export const METHODOLOGY_COUNT = 22;
