/**
 * OpenGraph image (1200×630) auto-generated by Next.js at build time.
 *
 * Renders the project's signature cyberpunk-terminal aesthetic for
 * LinkedIn / Twitter / Slack previews. The same file backs the
 * twitter-image too (see ../twitter-image.tsx — it re-exports this).
 *
 * Design choices, all deliberate:
 *  - Dark theme even though the site defaults to light. OG images are
 *    consumed on dark-mode social feeds (LinkedIn, Slack) far more often
 *    than light-mode; the dark variant reads better in both contexts.
 *  - Orbitron for the brand mark (matches the site's `--font-display`).
 *    Loaded via direct TTF fetch — Next.js `next/font` isn't available in
 *    Satori's rendering context (the `ImageResponse` server runtime is
 *    sandboxed and only supports raw fonts).
 *  - The five-row terminal `●` status block is the same motif as the
 *    landing page's <SystemStatus> component, so the OG image and the
 *    real site share visual identity at first glance.
 */

import { ImageResponse } from "next/og";

import { METHODOLOGY_COUNT } from "@/lib/methodology-count";

export const alt = "Asclepius — Biotech Venture Valuation";
export const size = { width: 1200, height: 630 };
export const contentType = "image/png";

// Cyberpunk dark palette. These match the project's `[data-theme="dark"]`
// CSS-var values from globals.css, kept in sync manually because Satori
// can't read CSS custom properties.
const BG_DEEP = "#0a0e16";
const BG_PANEL = "#0f141d";
const BORDER_DIM = "#2a3344";
const CYAN_BRIGHT = "#22d3ee";
const CYAN_FADED = "#0e8a8a";
const MAGENTA_BRIGHT = "#e879f9";
const AMBER_BRIGHT = "#fbbf24";
const TEXT_PRIMARY = "#c8d0dc";
const TEXT_DIM = "#6a7488";

export default async function Image() {
  // Pull Orbitron 700 + Share Tech Mono from Google Fonts. Both are
  // small (≤30KB) so the runtime cost is fine. We fail closed (fall back
  // to default sans-serif) if the fetch errors — the image still
  // renders, just without the brand typography.
  const [orbitronWeight, monoWeight] = await Promise.all([
    fetch(
      "https://fonts.googleapis.com/css2?family=Orbitron:wght@700&display=swap",
    )
      .then((r) => r.text())
      .then((css) => css.match(/src: url\((https:[^)]+)\)/)?.[1])
      .then((url) => (url ? fetch(url).then((r) => r.arrayBuffer()) : null))
      .catch(() => null),
    fetch(
      "https://fonts.googleapis.com/css2?family=Share+Tech+Mono&display=swap",
    )
      .then((r) => r.text())
      .then((css) => css.match(/src: url\((https:[^)]+)\)/)?.[1])
      .then((url) => (url ? fetch(url).then((r) => r.arrayBuffer()) : null))
      .catch(() => null),
  ]);

  const fonts = [];
  if (orbitronWeight) {
    fonts.push({
      name: "Orbitron",
      data: orbitronWeight,
      weight: 700 as const,
      style: "normal" as const,
    });
  }
  if (monoWeight) {
    fonts.push({
      name: "ShareTechMono",
      data: monoWeight,
      weight: 400 as const,
      style: "normal" as const,
    });
  }

  return new ImageResponse(
    (
      <div
        style={{
          width: "100%",
          height: "100%",
          display: "flex",
          flexDirection: "column",
          background: BG_DEEP,
          padding: "70px 80px",
          fontFamily: "ShareTechMono",
        }}
      >
        {/* Top row — version chip + URL pinned right. Status dots are
            rendered as CSS circles (not unicode `●`) because Satori
            won't fall back across fonts for missing glyphs. */}
        <div
          style={{
            display: "flex",
            justifyContent: "space-between",
            alignItems: "center",
            marginBottom: 48,
          }}
        >
          <div
            style={{
              display: "flex",
              alignItems: "center",
              fontFamily: "ShareTechMono",
              fontSize: 22,
              letterSpacing: "0.3em",
              color: TEXT_DIM,
              textTransform: "uppercase",
            }}
          >
            <div
              style={{
                width: 14,
                height: 14,
                borderRadius: 7,
                background: CYAN_BRIGHT,
                marginRight: 14,
              }}
            />
            v1.5.8 · MIT
          </div>
          <div
            style={{
              fontFamily: "ShareTechMono",
              fontSize: 22,
              letterSpacing: "0.2em",
              color: TEXT_DIM,
              textTransform: "uppercase",
            }}
          >
            asclepius-bio.vercel.app
          </div>
        </div>

        {/* Brand mark */}
        <div
          style={{
            fontFamily: "Orbitron",
            fontSize: 132,
            fontWeight: 700,
            letterSpacing: "0.04em",
            color: CYAN_BRIGHT,
            textTransform: "uppercase",
            lineHeight: 1,
            marginBottom: 18,
          }}
        >
          Asclepius
        </div>

        {/* One-line tagline */}
        <div
          style={{
            fontFamily: "ShareTechMono",
            fontSize: 30,
            color: TEXT_PRIMARY,
            letterSpacing: "0.04em",
            marginBottom: 64,
          }}
        >
          Biotech venture valuation · reflexivity-adjusted PoS · phase-gated rNPV
        </div>

        {/* "SYSTEM" separator. The horizontal rule is a CSS border on a
            div, NOT unicode dashes — same Satori glyph-fallback reason. */}
        <div
          style={{
            display: "flex",
            alignItems: "center",
            marginBottom: 22,
          }}
        >
          <div
            style={{
              width: 40,
              borderTop: `1px solid ${BORDER_DIM}`,
              marginRight: 14,
            }}
          />
          <div
            style={{
              fontFamily: "ShareTechMono",
              fontSize: 18,
              color: BORDER_DIM,
              letterSpacing: "0.25em",
            }}
          >
            SYSTEM
          </div>
          <div
            style={{
              flex: 1,
              borderTop: `1px solid ${BORDER_DIM}`,
              marginLeft: 14,
            }}
          />
        </div>

        {/* Five rows of `●` status lines — same motif as the live landing */}
        <div style={{ display: "flex", flexDirection: "column", gap: 8 }}>
          <StatusRow
            color={CYAN_BRIGHT}
            label="ML PoS PRIOR"
            detail="PubMedBERT + phase-stratified LightGBM"
            value="HINT + CTO trained"
          />
          <StatusRow
            color={MAGENTA_BRIGHT}
            label="REFLEXIVITY"
            detail="Spence signaling-equilibrium adjustment"
            value="headline differentiator"
          />
          <StatusRow
            color={AMBER_BRIGHT}
            label="EXTERNAL"
            detail="CT Open uncontaminated (Gao 2024)"
            value="AUC 0.600"
          />
          <StatusRow
            color={CYAN_FADED}
            label="METHODOLOGY"
            detail={`${METHODOLOGY_COUNT} cited writeups · every JSON value sourced`}
            value="MIT licensed"
          />
        </div>
      </div>
    ),
    { ...size, fonts: fonts.length ? fonts : undefined },
  );
}

interface StatusRowProps {
  color: string;
  label: string;
  detail: string;
  value: string;
}

function StatusRow({ color, label, detail, value }: StatusRowProps) {
  return (
    <div
      style={{
        display: "flex",
        alignItems: "center",
        fontFamily: "ShareTechMono",
        fontSize: 22,
        letterSpacing: "0.05em",
      }}
    >
      {/* CSS-circle status dot (Satori-safe; no unicode font fallback) */}
      <div
        style={{
          width: 14,
          height: 14,
          borderRadius: 7,
          background: color,
          marginRight: 18,
          marginTop: 2,
        }}
      />
      <span
        style={{
          color: TEXT_PRIMARY,
          textTransform: "uppercase",
          width: 220,
          letterSpacing: "0.15em",
        }}
      >
        {label}
      </span>
      <span style={{ color: TEXT_DIM, flex: 1 }}>{detail}</span>
      <span style={{ color, textTransform: "uppercase", letterSpacing: "0.1em" }}>
        {value}
      </span>
    </div>
  );
}
